apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellocuda-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/mvinkler/hellocuda-go
          resources:
            limits:
              nvidia.com/gpu: '1'